apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lqt4xyutg-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-k44rr.k44rr.sandbox1126.opentlc.com/tssc/rhtap-qe-dotnet-basic:8915fbc4ca8dcbb45098e06976c89bdda71e87d7@sha256:21be68daaf0b0029835b2e2444faa4363e04e295822c59a896a1566c96c6da47
          name: container-image
