apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lqt4xyutg-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-k44rr.k44rr.sandbox1126.opentlc.com/tssc/rhtap-qe-dotnet-basic:2844fa83a135c99cab61d0baf2b2105493323c0b@sha256:fbae707da6a21fbb6b040458992b565ad4c7f9877c3d440810663772f0abbcb3
          name: container-image
